// This file is generated by scripts/generate-app-metadata.mjs.
// Do not edit it manually; update package.json or the generator instead.
export const APP_METADATA = {
  "name": "LTR Trade",
  "version": "0.0.1",
  "buildTime": "2026-07-10T15:29:12.925Z"
} as const
